# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookTalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookTalk
	pod 'Alamofire'
	pod 'DGCharts'
	pod 'Kingfisher', '~> 8.0'
	pod 'lottie-ios'
	pod 'SnapKit', '~> 5.7.0'
	pod 'Then'
	pod 'KakaoSDKCommon'
	pod 'KakaoSDKAuth'
	pod 'KakaoSDKUser'
end
